name: Prepare L10n
on:
  workflow_call:
    outputs:
      branches:
        value: ${{ steps.config.outputs.branches }}
      path:
        value: ${{ steps.config.outputs.path }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.config.outputs.branches }}
      path: ${{ steps.config.outputs.path }}
    steps:
      - name: Checkout l10n repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          path: l10n
          ref: main

      - name: Get branches & path
        id: config
        run: |
          echo "branches=$(jq -c '.branches' < l10n/.github/update-config.json)" >> "$GITHUB_OUTPUT"
          echo "path=$(jq -r '.paths.fenix' < l10n/.github/update-config.json)" >> "$GITHUB_OUTPUT"
