name: Update L10n
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      branches:
        required: true
        type: string
      path:
        required: true
        type: string

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout android-l10n repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: l10n
          persist-credentials: false
          ref: main

      - name: Checkout mobile-android repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: source
          persist-credentials: false
          repository: mozilla-firefox/firefox
          sparse-checkout: |
            ${{ inputs.path }}

      - name: Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: l10n/.github/scripts/requirements.txt

      - name: Install Python dependencies
        run: pip install -r l10n/.github/scripts/requirements.txt

      - name: Run update.py for all branches
        run: |
          for branch in $(echo '${{ inputs.branches }}' | jq -r '.[]'); do
            echo "Processing branch: $branch"

            cd source
            git fetch origin $branch
            git checkout -B $branch origin/$branch
            cd ..

            python l10n/.github/scripts/update.py \
              --project ${{ inputs.project }} \
              --branch $branch \
              --commit $(cd source && git rev-parse --short HEAD) \
              --firefox source
          done
