# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: Update android-components

on:
  schedule:
    - cron: "5 15 * * 1,4"
  workflow_dispatch:

jobs:
  prepare:
    uses: ./.github/workflows/_prepare.yaml

  update:
    needs: prepare
    uses: ./.github/workflows/_update.yaml
    with:
      project: android-components
      branches: ${{ needs.prepare.outputs.branches }}
      path: ${{ needs.prepare.outputs.path }}

  cleanup:
    needs: update
    uses: ./.github/workflows/_cleanup.yaml
    with:
      project: android-components
      token: ${{ secrets.ANDROID_GITHUB_TOKEN }}
